name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main, deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build css
        run: |
          npm install
          npm run build

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'main'